### ISSUE TITLE
Feature Request - allow user can star certain problems

### ISSUE THREAD

**Issue by seungjun-green** [neetcode-gh/leetcode#1012]
**Feature Request**

What about adding a new feature that allow user can start certain problems on the neetcdoe website?

When practicing the Blind 75 list, I found some problems that I have to study/solve again. If I can star those problems on the neetcode website, I think it would make the life a little easier for people like me.

Thanks

**Comment by Ahmad-A0** [comment]
This seems like a duplicate of #364, please reopen if this isn't the case.
