### ISSUE TITLE
239 Sliding Window Maximum Python Solution

### ISSUE THREAD

**Issue by YeezyYeezyWhatsGood** [neetcode-gh/leetcode#1015]
In [NeetCode's video solution](https://www.youtube.com/watch?v=DfljaUwZsOk&ab_channel=NeetCode) he only uses one deque to keep track of the indexes but in [the python solution here](https://github.com/neetcode-gh/leetcode/blob/main/python/239-Sliding-Window-Maximum.py) two deques are used, one keeping track of the index and the other keeping track of the value. Additionally you unnecessarily changed a while statement to an if statement. I made some changes to make the solution closer to the solution presented in the video as well as more efficient and readable
```python
class Solution:
    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:
        index_q = deque()

        res = []
        for i, n in enumerate(nums):
            while index_q and n > nums[index_q[-1]]:
                index_q.pop()
            index_q.append(i)

            if index_q[0] == i - k:
                index_q.popleft()
            if i + 1 >= k:
                res.append(nums[index_q[0]])
        return res
```

**Comment by Ahmad-A0** [comment]
Thanks, @YeezyYeezyWhatsGood. I've set the solution to be exactly the same as the neetcode video so that there's no confusion the site.

**Comment by YeezyYeezyWhatsGood** [comment]
@Ahmad-A0 Thank you for making this change but on line 7 there is a typo it says
```python
while l < len(nums):
```
But should say
```python
while r < len(nums):
```
As it is the code fails with IndexError: List index out of range on line 9.

**Comment by Ahmad-A0** [comment]
Sorry about that, thanks @YeezyYeezyWhatsGood!
