### ISSUE TITLE
235. Lowest Common Ancestor of a Binary Search Tree - Changed Difficulty

### ISSUE THREAD

**Issue by duranbe** [neetcode-gh/leetcode#1073]
The level changed on LeetCode, it's a medium question while Neetcode says easy.

https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/
https://neetcode.io/practice

Feel free to close if you consider keeping the easy tag.

Have a nice day !

**Comment by vrindavan** [comment]
Was just coming to open this issue haha.

**Comment by neetcode-gh** [comment]
Fixed.
