### ISSUE TITLE
40-Combination-Sum-II.py gives wrong answer

### ISSUE THREAD

**Issue by GraydenH** [neetcode-gh/leetcode#1099]
https://github.com/neetcode-gh/leetcode/blob/main/python/40-Combination-Sum-II.py

This solution fails and gives the wrong answer

**Comment by YeezyYeezyWhatsGood** [comment]
I just ran it and it worked for me- maybe you aren't on python3 or something weird?
![image](https://user-images.githubusercontent.com/28869518/189517914-9b2e8db5-6a59-4e6a-b96c-21ff3b8b9e1b.png)

**Comment by GraydenH** [comment]
I tried it again and it worked, not sure what happened. Maybe theres a bug in leetcode
