### ISSUE TITLE
Not able to save Progress in Neetcode 150

### ISSUE THREAD

**Issue by abhisinha4395** [neetcode-gh/leetcode#1121]
Hi, 
   my progress in neetcode 150 is getting reset after every page refresh or by signing out. Not sure, if other people also facing the same issue.

**Comment by vlfldr** [comment]
same issue for the past ~week

it would also be nice to have a way of saving progress which does not rely on cookies/SSO buttons

**Comment by sasilver75** [comment]
Still hittin this big dawg
