### ISSUE TITLE
add aakhtar3 as a collaborator

### ISSUE THREAD

**Issue by mitchellirvin** [neetcode-gh/leetcode#1145]
hi @neetcode-gh ! 

@aakhtar3 has been a [terrific contributor to this repo](https://github.com/neetcode-gh/leetcode/pull/464#issuecomment-1200289590). would you mind adding them as a collaborator?

**Comment by neetcode-gh** [comment]
Done, just invited @aakhtar3 Really appreciate the contributions!!
