### ISSUE TITLE
JS solution no available to LC25

### ISSUE THREAD

**Issue by tofunaor** [neetcode-gh/leetcode#1146]
JS solution to 25. Reverse nodes in k-group is [not available on github](https://github.com/neetcode-gh/leetcode/blob/main/javascript/25-Reverse-Nodes-in-K-Group.js).

 on the NC website it mistakenly shows solution of 23. merge k sorted list to this problem 25. Reverse nodes in k-group.

Please fix it.

**Comment by aakhtar3** [comment]
@tofunaor solution is up
[javascript/25-Reverse-Nodes-in-K-Group.js](https://github.com/neetcode-gh/leetcode/blob/main/javascript/25-Reverse-Nodes-in-K-Group.js)
