### ISSUE TITLE
JS solution to LC11 is wrong

### ISSUE THREAD

**Issue by tofunaor** [neetcode-gh/leetcode#1163]
Js solution to 11-Container-With-Most-Water has a minor mistake in the while loop.
it should be

```
const isRightGreater = leftHeight <= rightHeight;
        if (isRightGreater) left++;

   else right--;


```

otherwise, LC returns `wrong answer`

Please fix it

**Comment by aakhtar3** [comment]
Thanks. Will fix this

**Comment by aakhtar3** [comment]
@tofunaor, looking at the solution, there is nothing wrong with the code.

This is more of a style preference. Where the code is written to avoid else statements.

**Comment by tofunaor** [comment]
> @tofunaor, looking at the solution, there is nothing wrong with the code.
> 
> This is more of a style preference. Where the code is written to avoid else statements.

Nope, it generates a `wrong answer` on LeetCode.

**Comment by aakhtar3** [comment]
Here is my submission
https://leetcode.com/submissions/detail/806378136/
