### ISSUE TITLE
Two solutions exists for same problem in Kotlin

### ISSUE THREAD

**Issue by a93a** [neetcode-gh/leetcode#1661]
For this following problem [33. Search in Rotated Sorted Array](https://leetcode.com/problems/search-in-rotated-sorted-array/) there exists two different solutions in Kotlin with the following names:

**33_Search_In_Rotated_Sorted_Array.kt** 

and 

**0033-search-in-rotated-sorted-array.kt**

Should delete one (latest?) or merge the two into same file?

**Comment by tahsintunan** [comment]
I believe we should keep the most performant solution from the two (in terms of time and space complexity) and keep the correct naming convention (e.g. `0033-search-in-rotated-sorted-array.kt`). If both of them have similar time and space complexity, we can keep the one with more readability. We can remove the other one.

**Comment by neetcode-gh** [comment]
fixed
