### ISSUE TITLE
Request for collaborator permissions

### ISSUE THREAD

**Issue by AP-Repositories** [neetcode-gh/leetcode#1851]
Hello @neetcode-gh,

I've made some contributions, and I'd like to ask for collaborator permissions so I can merge them in the future.

**Comment by NikSWE** [comment]
I believe the best way would be to fork and add your changes after that just start a pull request so the maintainer of this repo can merge those changes for you.

**Comment by neetcode-gh** [comment]
Done. Thanks for the contributions!
