### ISSUE TITLE
Adding multiple solutions

### ISSUE THREAD

**Issue by gabr0236** [neetcode-gh/leetcode#189]
Hey Neetcode, can i add different solutions to existing problems? If so, should i add the solution to the existing solution file?

For me personally, it really helps to look at different solutions to understand the problem completely.

**Comment by mitchellirvin** [comment]
hi @gabr0236 ! i think for problems that have multiple distinct solutions (even if they're not equally efficient) it would be great to include them all.

maybe we should have a comment block for each solve that outlines (at least) the time/space complexity?

**Comment by mitchellirvin** [comment]
@neetcode-gh i figure it's not worth blocking on this. I'll +1 these types of PRs as I review them. we can rewind if you think we shouldn't?
