### ISSUE TITLE
Pull Request with Lintcode url when we don't have LC premium

### ISSUE THREAD

**Issue by josuebrunel** [neetcode-gh/leetcode#1909]
Hello guys, 
Thanks for the good work you're doing and the community you're building.
Can we submit URL from **Lintcode** when we don't have LC premium? 
Thanks

**Comment by neetcode-gh** [comment]
Yeah thats fine with me. But please be extra careful to make sure the solution is something that would also pass on LC. 

Sometimes there's not a one-to-one mapping between LC and lintcode problems. The lintcode problems can be slightly different

**Comment by josuebrunel** [comment]
Thanks got it.
