### ISSUE TITLE
leetcode submission links are not working.

### ISSUE THREAD

**Issue by Maunish-dave** [neetcode-gh/leetcode#2034]
Seems like leetcode submission links are not working, as usual, might have to change the PR template

Link: https://leetcode.com/problems/continuous-subarray-sum/submissions/878463146/

This is shown if I go to the submission from my account. 
![image](https://user-images.githubusercontent.com/44360315/212528078-7014fe74-2ebb-4d40-9795-e966dd0e7fb4.png)

But if I click on the above link I get a 404
![image](https://user-images.githubusercontent.com/44360315/212528138-1500ba43-61cb-4d49-8388-6d64f81017e7.png)

**Comment by tahsintunan** [comment]
Seems that a lot of people are facing the same problem (see [this](https://leetcode.com/discuss/general-discussion/3050539/LeetCode-404-not-found-Bug-on-Multiple-Pages.)). But this is happening with only some of the submission links, not all of them. Let's hope Leetcode fixes this problem soon.

**Comment by neetcode-gh** [comment]
Hmm, I wonder if that's a temporary bug or if LC is making this change permanent. 

For now I will wait and leave things as-is, because it still encourages people to make sure their solution passes on LC.

**Comment by tahsintunan** [comment]
Hey @Maunish-dave, it seems that Leetcode has resolved the issue (see [here](https://leetcode.com/discuss/general-discussion/3050539/Resolved-LeetCode-404-not-found-Bug-on-Multiple-Pages./1759687)). So I'm closing this issue :)
