### ISSUE TITLE
Question regarding contributions

### ISSUE THREAD

**Issue by a93a** [neetcode-gh/leetcode#2175]
I have a question for @neetcode-gh .

I have collaborator access on the repo, and usually when I contribute, I push to my remote, open a PR, fill in the template and merge it myself. I was wondering, if it is ok to skip this step, and directly push to this repo from my local machine?

Thanks in Advance.

**Comment by neetcode-gh** [comment]
Yeah, that's fine with me. As long as youre confident in your changes.
