### ISSUE TITLE
Multiple duplicates for C++

### ISSUE THREAD

**Issue by a93a** [neetcode-gh/leetcode#2176]
There exists a lot of duplicates in the cpp map. Under cpp/neetcode_150 there are 150 solution with different filename style, of which most exists already in the cpp map with the correct filenames. 

I was wondering if you want to keep it that way, or need help to sort it out? @neetcode-gh

**Comment by neetcode-gh** [comment]
Yeah i think the entire `cpp/neetcode_150` folder can be deleted now. If you do it, feel free to assign the PR to me

**Comment by a93a** [comment]
Alright, I'll do that. Will double check for any non duplicates in there also.
