### ISSUE TITLE
Lowest Common Ancestor of a BST

### ISSUE THREAD

**Issue by Fa7mY** [neetcode-gh/leetcode#221]
Since the question specifies a **Binary Search Tree**, and that `q` and `p` are nodes in the tree, the solution can be further simplified to be a search for the node whose value is between `p` and `q`

for instance
```
class Solution:
    def lowestCommonAncestor(self, root: 'TreeNode', p: 'TreeNode', q: 'TreeNode') -> 'TreeNode':
        if p.val <= root.val <= q.val or p.val >= root.val >= q.val:
            return root
        
        if p.val < root.val and q.val < root.val:
            return self.lowestCommonAncestor(root.left, p, q)
        else:
            return self.lowestCommonAncestor(root.right, p, q) 
```

**Comment by alfinm01** [comment]
Or maybe even better, doing it iteratively:
```go
func lowestCommonAncestor(root, p, q *TreeNode) *TreeNode {
    for root != nil {
        if p.Val < root.Val && q.Val < root.Val {
            root = root.Left
        } else if p.Val > root.Val && q.Val > root.Val {
            root = root.Right
        } else {
            return root
        }
    }
    
    return nil
}
```

**Comment by cd412** [comment]
The site links to the problem [235. Lowest Common Ancestor of a Binary Search Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/) and the python solution links to[ 236-Lowest-Common-Ancestor-of-a-Binary-Tree.py ](https://github.com/neetcode-gh/leetcode/blob/main/236-Lowest-Common-Ancestor-of-a-Binary-Tree.py). So it seems that's why the answer does not take advantage of the BST property.

**Comment by abe-101** [comment]
> The site links to the problem [235. Lowest Common Ancestor of a Binary Search Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/) and the python solution links to[ 236-Lowest-Common-Ancestor-of-a-Binary-Tree.py ](https://github.com/neetcode-gh/leetcode/blob/main/236-Lowest-Common-Ancestor-of-a-Binary-Tree.py). So it seems that's why the answer does not take advantage of the BST property.

Yes I can confirm this
On the site the leetocde link, the walk through video, the solution in java and c++ are all leetcode problom 235.
The python solution is mistakenly linked to [236](https://github.com/neetcode-gh/leetcode/blob/main/236-Lowest-Common-Ancestor-of-a-Binary-Tree.py)

PR #578 add problem 235 in python

**Comment by neetcode-gh** [comment]
Will update the link this weekend.
