### ISSUE TITLE
Adding solutions that are not on the list?

### ISSUE THREAD

**Issue by a93a** [neetcode-gh/leetcode#2227]
Can I add solutions for problems not on the list on the README.md ? And when they are added check so that the solution are up-to-date with your solution ? Or should I wait until they appear on the list? @neetcode-gh

**Comment by a93a** [comment]
To clarify. I mean both solutions that are not on the list + you have not solved/made a video for yet, and solutions you also have solved/made a video for but not on the list.

**Comment by neetcode-gh** [comment]
I think it would be fine, but what would be the purpose for adding a problem that isn't on the site & doesn't have a video for it?

**Comment by a93a** [comment]
@neetcode-gh I think you are right. I just added all the other solutions you have made a video for, but that hasn't appeared on the repo Readme yet.
