### ISSUE TITLE
Javascript 125-ValidPalindrome.js solution is not implemented correctly

### ISSUE THREAD

**Issue by Martin-Karsten** [neetcode-gh/leetcode#242]
As the title says the solution is not correct. There are two problems.
First it should check if the character is not alphanumeric in the while loops. The current solution checks if it is alphanumeric
Second the isAlphaNumeric method is implemented incorrectly.

**Comment by imaginate** [comment]
These problems were resolved by an earlier [pull request](https://github.com/neetcode-gh/leetcode/commit/1adba3f77089f8982d480771fe3abe9b6e19c8fb), and the solution was further cleaned up with this [commit](https://github.com/neetcode-gh/leetcode/commit/9a02b70ac517e294d3c6e0b9af85b65c83e6e8d9). Thanks for opening the issue and pull request!
