### ISSUE TITLE
[site feature request] add ability to reset progress while signed in

### ISSUE THREAD

**Issue by iamtodor** [neetcode-gh/leetcode#2587]
Add the ability to reset progress while signed in

**Comment by kd10041** [comment]
This feature is already available on the neetcode.io website.

![Delete Progress feature](https://github.com/neetcode-gh/leetcode/assets/108215376/1f063754-4f29-4608-a4b1-d5931bacb1e1)

Checkout the image above: the delete icon with white underlined

**Comment by iamtodor** [comment]
Closing the issue as its done :)
