### ISSUE TITLE
Add an option to export and import progress

### ISSUE THREAD

**Issue by navinthomas** [neetcode-gh/leetcode#259]
Currently, the progress on the site can be lost when the browser cache is cleared, browser is reinstalled, etc. I think it would be great if an export/import progress feature is added to the site, so that users can back up their progress. It would also be useful in cases like when a user wants to use the site in a different computer. They can export the progress in the old computer and import it in the new computer's browser to resume progress on the new machine.

**Comment by Ahmad-A0** [comment]
I think the login feature means I can close this now.
