### ISSUE TITLE
JavaScript solution for Valid Sudoku: out of bounds assignment using char coercion

### ISSUE THREAD

**Issue by dimxnux** [neetcode-gh/leetcode#2640]
https://github.com/neetcode-gh/leetcode/blob/39611acc774b207757a978bb0f630b1bf7466529/javascript/0036-valid-sudoku.js#L36-L41

When `char = '1'` the second column is referenced and when `char = '9'` the 10th column is referenced which is undefined, but doesn't make the program to fail. There is an offset of 1 at each reference to the columns.

Instead, `1` should be subtracted from `char` i.e. `char - 1`, to get the correct column index.

**Comment by aakhtar3** [comment]
Fixed!

JS, allows flexible dynamic arrays, and undefined is considered falsey. Which allows the code to pass when operating out of bounds.
