### ISSUE TITLE
New Python Folder accidentally added created a new column in the ReadMe.

### ISSUE THREAD

**Issue by felivalencia3** [neetcode-gh/leetcode#2760]
Hello,

Yesterday I merged a pull request: #2754
that had its code under a "python " folder (with a space at the end). I did not notice this when I reviewed it focused on reviewing the code. I noticed a few minutes ago that this had happened and that the automatic Github Action had built a new column in the README for this new "python " folder. I quickly moved the file into the main python folder, closed the misnamed folder, and reran the README Github Action hoping that this would automatically remove the extra "python" column. However, it didn't. 

I'm not sure how to fix this, any help would be appreciated.

**Comment by Ahmad-A0** [comment]
The README table is generated automatically by a GitHub workflow script that runs every hour, you were probably unlucky enough that it ran exactly after you made your change. I've manually re-ran the script to fix the column although it would have fixed itself on the hour anyway :P. For future reference I believe collaborators can run the script directly in the "Actions" column in the top bar.
