### ISSUE TITLE
The solution https://github.com/neetcode-gh/leetcode/blob/main/python/0004-median-of-two-sorted-arrays.py can't pass test cases anymore

### ISSUE THREAD

**Issue by iharkatkavets** [neetcode-gh/leetcode#3019]
Hello, 

I watched the video https://www.youtube.com/watch?v=q6IEA26hvXc
and tried to apply the solution, but it can't pass all test cases anymore
<img width="799" alt="image" src="https://github.com/neetcode-gh/leetcode/assets/1083951/3e177824-7534-4072-919d-056b2df12b4e">

Just FYI
Have a good day

**Comment by udyanojha** [comment]
Hi, @iharkatkavets I just checked the solution it's getting submitted. 
Give it a try now.
The solution from the link mentioned in the title i.e. [Solution link](https://github.com/neetcode-gh/leetcode/blob/main/python/0004-median-of-two-sorted-arrays.py) is working. :)
