### ISSUE TITLE
132-pattern Problem Labeled incorrectly

### ISSUE THREAD

**Issue by sujal-goswami** [neetcode-gh/leetcode#3034]
The problem number is incorrect for 132 pattern problem it should be `0456` not 0132.

**Comment by sujal-goswami** [comment]
Hey @neetcode-gh ,
Please fix this in Readme.md , as I cannot do so.

**Comment by neetcode-gh** [comment]
Thanks for letting me know.

I will add this to my TODO list, because it will require a quick change to the neetcode.io site as well. I will handle renaming the problem number for all the solutions.
