### ISSUE TITLE
0078-subsets.py AttributeError: 'list' object has no attribute 'copy'

### ISSUE THREAD

**Issue by Mohamed-Aziz-Ben-Nessir** [neetcode-gh/leetcode#3250]
The copy method does not work in python 2

**Comment by Mohamed-Aziz-Ben-Nessir** [comment]
@neetcode-gh Should I replace it in all of the copy methods in the backtracking solutions and make one pr of all of it?

**Comment by Niyaz2498** [comment]
Hi @Mohamed-Aziz-Ben-Nessir I am trying to understand if i missed something. Copy method works fine in python 3. 
https://leetcode.com/problems/subsets/submissions/1156481251/
please check the above submission where I used copy and it succeeded.

**Comment by Mohamed-Aziz-Ben-Nessir** [comment]
oh! my bad I meant to say python 2. if we just change it to just [:] it will just work for both and it's faster.
