### ISSUE TITLE
Neetcode Youtube video used Bellman Ford but solution on website is using Modified Dijkstra's

### ISSUE THREAD

**Issue by adityaiiitr** [neetcode-gh/leetcode#3266]
Leetcode Question [787. Cheapest Flights Within K Stops](https://leetcode.com/problems/cheapest-flights-within-k-stops/)

Solution Provided: [Github Solution](https://github.com/neetcode-gh/leetcode/blob/main/cpp/0787-cheapest-flights-within-k-stops.cpp)

Neetcode video: [YT Link ](https://www.youtube.com/watch?v=5eIK3zUdYmE)

**Comment by a93a** [comment]
Has been fixed
