### ISSUE TITLE
[site feature request] add task progress granularity

### ISSUE THREAD

**Issue by iamtodor** [neetcode-gh/leetcode#327]
I would like to suggest adding granularity in the site https://neetcode.io/ (Easy / Medium / Hard) to the problems for better visibility and tracking
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/12586108/174477484-1c5e727c-089f-4efb-bdcb-bd9c48283b33.png">

**Comment by iamtodor** [comment]
It's not stale @neetcode-gh

**Comment by neetcode-gh** [comment]
Thanks for the suggestion, this is something I planned on adding a while back but never got around to it. Should be able to get this done relatively soon

**Comment by iamtodor** [comment]
@neetcode-gh I would like to check on it :)

**Comment by iamtodor** [comment]
Closing the issue as its done
<img width="241" alt="image" src="https://github.com/neetcode-gh/leetcode/assets/12586108/43729e15-f394-41b5-bc77-96e7f6f83d3b">
