### ISSUE TITLE
Should be minimumVal(root.right)

### ISSUE THREAD

**Issue by MeganYTan** [neetcode-gh/leetcode#3272]
https://github.com/neetcode-gh/leetcode/blob/755a89a60c3b13ddd96c4055279aefac4ac6a66a/java/0450-delete-node-in-a-bst.java#L27

This solution does not work. It should be minimumVal(root.right)

**Comment by a93a** [comment]
That's true, good catch.

Do you want to open a PR with the change, or want me to change it for you ?

**Comment by Inamul07** [comment]
@a93a I have made the changes relating to this issue, and i have also added two solutions in java, which were marked X in the ReadMe table. PR #3329
