### ISSUE TITLE
Feature Request: Button to shuffle categories

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [neetcode-gh/leetcode#339]
It would be nice to be able to shuffle the categories. I mean only the categories, NOT the order of problems inside each category.
Normally, we could split our DSA interview study into 2 rounds:
1. Learning with easy questions
    I think we shouldn't use this feature in this round.
3. Practicing with medium then hard questions:
    In this round, randomness (emphasis, only categories, not the content inside each category) could be very helpful to many people like me, especially when combine with https://github.com/neetcode-gh/leetcode/issues/336.

**Comment by nguyenxndaidev** [comment]
@neetcode-gh I would like to create PR to the website code but couldn't find it. Do you also want to opensource your website code?
