### ISSUE TITLE
Kindly Review This PR and Merge It

### ISSUE THREAD

**Issue by abdulrafayl226825** [neetcode-gh/leetcode#3639]
#3635

**Comment by prasanth50** [comment]
Please add the describtion to your PR to get this reviewd.

**Comment by abdulrafayl226825** [comment]
> Please add the describtion to your PR to get this reviewd.

Could you please guide me on how and what to add in the description, whether it's about the code or something else?

**Comment by Ykhan799** [comment]
@abdulrafayl226825 Follow the https://github.com/neetcode-gh/leetcode/blob/main/CONTRIBUTING.md guidelines
