### ISSUE TITLE
Feature Req: Close Youtube Popup Modal on "esc" key press

### ISSUE THREAD

**Issue by rikotacards** [neetcode-gh/leetcode#421]
Would find it highly convenient if we added the ability to close the Youtube popup modal on "esc" keypress

**Comment by rikotacards** [comment]
Would be happy to work on that too btw.

**Comment by nimpadjio** [comment]
Would like to work on this issue

**Comment by neetcode-gh** [comment]
Sorry it took so long, but this has been fixed.
