### ISSUE TITLE
74-Search-A-2D-Matrix.java is not a Binary Search

### ISSUE THREAD

**Issue by AmonKip** [neetcode-gh/leetcode#442]
The Java solution is a linear search and NOT a binary search. Worst case runtime for the code is O(m+n) which occurs if the target value is at the bottom left corner of the matrix. Binary search solution should be O(logm) + O(logn) as described in the video solution.

**Comment by Ahmad-A0** [comment]
Area you talking about [744-Binary-Search.java](https://github.com/neetcode-gh/leetcode/blob/main/java/704-Binary-Search.java)

```java
```

**Comment by AmonKip** [comment]
Yes it's leetcode problem #74. Sorry, I was specific enough.
