### ISSUE TITLE
What type of license this repo has? Could you publish the LICENSE file to let know others how people can use the sources?

### ISSUE THREAD

**Issue by smartchecksum** [neetcode-gh/leetcode#458]
Hey guys, hi @neetcode-gh, awesome site! i find a lot of solutions very useful but can i share them with students on lectures or in youtube videos? [The LICENSE file ](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)would be great to have to let know others how people can use the sources. Could you release one?

Github has great page dedicated to opensource licenses: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

All the best!

**Comment by smartchecksum** [comment]
@neetcode-gh @Ahmad-A0 Hey, hope you're doing well! Any updates on the license? Would you guys be ok if i make a PR with MIT version?

**Comment by Ahmad-A0** [comment]
Sorry for the delay, I'm not sure about the LICENSE situation either but would also be in favour of an MIT License. Thoughts @neetcode-gh?

**Comment by neetcode-gh** [comment]
Yeah MIT license is fine with me.
