### ISSUE TITLE
Add leading zeros to file name to keep them in order

### ISSUE THREAD

**Issue by abe-101** [neetcode-gh/leetcode#463]
A neat little python script can add leading zero's to all the file names this way they will appear in order.
Something like this:
```python
import sys,os,re

for file in sys.argv[1:]:
    if __file__ in file: continue
    number, name = file.split('-', 1)
    number = '{:0>4}'.format(number)
    new_name = f'{number}-{name}'
    os.rename(file,new_name)
```
PR #335 is the result of the above program.

**Comment by MeViMo** [comment]
It's worth noting that this is very closely related to #457. They should probably be part of the same proposal since they both require the website to be updated.

**Comment by mitchellirvin** [comment]
Closing in favor of #457, which will include this change!
