### ISSUE TITLE
Defect JS Solution: 102. Binary Tree Level Order Traversal

### ISSUE THREAD

**Issue by bmoes-coderoom** [neetcode-gh/leetcode#472]
The provided Javascript solution for [LeetCode 102. Binary Tree Level Order Traversal](https://github.com/neetcode-gh/leetcode/blob/e815ef40362f73d06aba13c558e4bed5bad756ba/javascript/102-Binary-Tree-Level-Order-Traversal.js) has a defect when the input array is an empty array

The error being returned is:
```
Line 23 in solution.js
            temp.push(subtree.val)
                              ^
TypeError: Cannot read properties of null (reading 'val')
    Line 23: Char 31 in solution.js (levelOrder)
    Line 42: Char 19 in solution.js (Object.<anonymous>)
    Line 16: Char 8 in runner.js (Object.runner)
    Line 33: Char 26 in solution.js (Object.<anonymous>)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```
![Error](https://user-images.githubusercontent.com/10567180/178605910-5ced56e4-dd5a-4f7f-9418-e696a6c33094.png)
![TestInput](https://user-images.githubusercontent.com/10567180/178606082-6a6e4ab8-a291-443a-a49b-b4e785762367.png)

**Comment by bmoes-coderoom** [comment]
@thisiswhale I think you contributed the solution so maybe you can help?

**Comment by thisiswhale** [comment]
Thanks for the catch! Need to add at the top 

`if(!root)` return [];`
