### ISSUE TITLE
Find Duplicate Number should  not be under Linked List

### ISSUE THREAD

**Issue by minecx** [neetcode-gh/leetcode#473]
The 8th challenge in Linked List says [Find the Duplicate Number](https://leetcode.com/problems/find-the-duplicate-number/) but its related topics are array, 2 pointers, binary search and bit manipulation instead. Maybe move this to another group?

**Comment by neetcode-gh** [comment]
The optimal solution for this problem is based on linked lists, so will leave this as-is.
