### ISSUE TITLE
C# Solutions

### ISSUE THREAD

**Issue by nathanielsuchy** [neetcode-gh/leetcode#49]
In the future will it be possible to contribute C# solutions. I know the language is very similar to Java (although with many major differences) but as an engineer who is "all in" on Microsoft, .NET, and ASP it'd be nice to have C# solutions available. I'd be happy to contribute some as I learn.

**Comment by ranamahmud** [comment]
Adding C# solutions will be very helpful.

**Comment by ShreyasJejurkar** [comment]
I was looking for the same. I will also add solutions!

**Comment by ranamahmud** [comment]
@irlcatgirl You might close this issue as now c# solutions can be added.

**Comment by AhmedShabaanHelwa** [comment]
I am a C# developer and wanna share my solutions here isA.
