### ISSUE TITLE
Use of lowercase "L" as a variable

### ISSUE THREAD

**Issue by bcatalfo** [neetcode-gh/leetcode#588]
According to [PEP 8](https://peps.python.org/pep-0008/#names-to-avoid) 

> Never use the characters ‘l’ (lowercase letter el), ‘O’ (uppercase letter oh), or ‘I’ (uppercase letter eye) as single character variable names. In some fonts, these characters are indistinguishable from the numerals one and zero. When tempted to use ‘l’, use ‘L’ instead.

However several of these solutions use lowercase 'l' usually as a "left" pointer in conjunction with a "right" pointer indicated by 'r'. Personally I would recommend changing these to "L" and "R" but really anything is okay as long as it isn't "l" as it is very confusing. Examples of problems that use this are 424-Longest-Repeating-Character-Replacement and 647-Palindromic-Substrings.

**Comment by MeViMo** [comment]
PEP8 also says variables should be lowercase, so definitely not `R`. For optimal readability these kinds of variables should be named `left` and `right` in full.
That being said, `l, r = 0, 1` should be plenty self-descriptive for Leetcode solutions.
