### ISSUE TITLE
Option to view all languages

### ISSUE THREAD

**Issue by DanMossa** [neetcode-gh/leetcode#623]
With the new style change I have to go back and forth between programming language tabs.

More context here

https://github.com/neetcode-gh/leetcode/pull/600#issuecomment-1193478057

**Comment by neetcode-gh** [comment]
Thanks for the suggestion, done! Please confirm that it works as expected, and then feel free to close. Thanks!

**Comment by DanMossa** [comment]
You're god's gift to mankind.
Thank you
