### ISSUE TITLE
Duplicate Solution: 215-Kth-Largest-Element-in-an-Array.py

### ISSUE THREAD

**Issue by abe-101** [neetcode-gh/leetcode#628]
It seams the python code in this solution is a mix of two seperate approaches:

1. Sort and return kth element. N log N runtime
https://github.com/neetcode-gh/leetcode/blob/baff88f8772b1a7a75614f3c937407f5388015d9/python/215-Kth-Largest-Element-in-an-Array.py#L3-L4
2. QuickSelect. Linear runtime on average
https://github.com/neetcode-gh/leetcode/blob/baff88f8772b1a7a75614f3c937407f5388015d9/python/215-Kth-Largest-Element-in-an-Array.py#L6-L26

I would advise to separate into two separate functions or at a minimum use comments to clarify.

**Comment by KC10201** [comment]
I made a PR to refactor the solution into two separate classes. #668
