### ISSUE TITLE
Java solution of 572 - Subtree of Another Tree does not pass the required tests

### ISSUE THREAD

**Issue by elyasmasrour** [neetcode-gh/leetcode#664]
Java solution of 572 - Subtree of Another Tree fails when the following is presented as input:

[1,1]
[1]

(which is a Leetcode test case that it fails, making the solution incorrect)

**Comment by KC10201** [comment]
Made a PR to fix the solution. #667

**Comment by Shidhanta** [comment]
One test case that it is failing on is : 
[1,1]
[1]
Solution cant tell that the subtree has been completely found if there is a single node

**Comment by KC10201** [comment]
solution has been updated, and this issue can be closed now.
