### ISSUE TITLE
Python Group Anagram solution less efficient

### ISSUE THREAD

**Issue by matthewnbrown** [neetcode-gh/leetcode#708]
The Python solution listed uses a comparison sort rather than the counting sort shown in original solution video. This changes the time complexity from O(n * m) to O(n * m*log(m)).

The comparison sort probably runs faster on LeetCode because of small test cases and Python being slower than C, but it's still worse time complexity.

**Comment by Ahmad-A0** [comment]
Thanks, @matthewnbrown, nice spot! I fixed this in ca18e86fb302ac508221db3046af75467cd4cefb but forgot to close this issue.
