### ISSUE TITLE
Can I add code visualization for better understanding for each examples? 

### ISSUE THREAD

**Issue by hisnameispum** [neetcode-gh/leetcode#744]
For example: 
https://pythontutor.com/render.html#code=def%20lengthOfLongestSubstring%28s%3A%20str%29%3A%0A%20%20%20%20longest_streak%20%3D%200%0A%20%20%20%20l%20%3D%200%0A%20%20%20%20charSet%20%3D%20set%28%29%0A%20%20%20%20for%20r%20in%20range%28len%28s%29%29%3A%0A%20%20%20%20%20%20%20%20while%20s%5Br%5D%20in%20charSet%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20charSet.remove%28s%5Bl%5D%29%0A%20%20%20%20%20%20%20%20%20%20%20%20l%20%2B%3D%201%0A%20%20%20%20%20%20%20%20charSet.add%28s%5Br%5D%29%0A%20%20%20%20%20%20%20%20longest_streak%20%3D%20max%28longest_streak,%20r-l%2B1%29%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20return%20longest_streak%0A%0AlengthOfLongestSubstring%28%22abcabcbb%22%29&cumulative=false&curInstr=37&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false

**Comment by Ahmad-A0** [comment]
I don't understand how something like this would be added to a text solution. Can you please elaborate?

**Comment by hisnameispum** [comment]
Yes! We could add this as a link in a much cleaner way using .md file format. I think it's really useful for complex problems such as recursions or backtracking that requires us to see step-by-step execution.

**Comment by Ahmad-A0** [comment]
I definitely think this is a useful tool for understanding how the solutions work, but making sure it is added to all new and existing solutions could be a hassle. Perhaps it would be better to add a list of resources that work well alongside Neet's video in the `readme` with this one being included?

**Comment by hisnameispum** [comment]
Yeah, that sounds optimized and useful.
