### ISSUE TITLE
Dynamically link solutions to site?

### ISSUE THREAD

**Issue by Ahmad-A0** [neetcode-gh/leetcode#763]
With the exception of the `cpp` and `.github` directory, all directories are in the format `<language-name>` which should match the tag needed on [neetcode.io](https://neetcode.io). Furthermore all files follow the `<problem-number>-Name-of-Problem.<language-extension>` naming scheme.

**Would it possible to slice the `<problem-number>` to dynamically link solutions?** This would have the added benefits of allowing issues like #463 which require mass renaming of files to be resolved.

@neetcode-gh

**Comment by neetcode-gh** [comment]
Yeah I agree with this. I think it's unfortunate we started with inconsistent naming, and the problem numbers not having leading zeroes, that was my bad. I will look into this soon and revisit. Thanks for all the hard work btw!!
