### ISSUE TITLE
[FEATURE REQUEST] : Pressing escape should close the window that opens.

### ISSUE THREAD

**Issue by dhruvmaindola227** [neetcode-gh/leetcode#779]
When we click on the question mark to the side of language selector(About window) , we should be able to close it simply by clicking escape. Right now we have to click on the close button to do so. Same escape button functionality should be there for when we click on CODE in the list and it shows the code for that question. 

![image](https://user-images.githubusercontent.com/80943305/183897934-4fdb8b8e-8e66-476f-aea5-c43fdf00402b.png)

**Comment by Ahmad-A0** [comment]
I'll link this to #421 because I think the implementation would be similar.
