### ISSUE TITLE
Dark mode for solution popup as well

### ISSUE THREAD

**Issue by vrindavan** [neetcode-gh/leetcode#834]
Currently, it is just in light mode, we can replace the background with a dark color. The color could be dark gray or blue like the Material Dark Themes from Google instead of the total black/AMOLED one.

![image](https://user-images.githubusercontent.com/50140643/184727588-a312cc27-6736-4f56-81df-d0d71d4571e4.png)

**Comment by jithu7432** [comment]
Would appreciate it if the table is also in dark mode!
