### ISSUE TITLE
Progress not being shown while signed-in

### ISSUE THREAD

**Issue by Vamsi995** [neetcode-gh/leetcode#845]
![image](https://user-images.githubusercontent.com/52487689/185135532-af1b9fd5-bc79-4f4e-8204-2606be2c5588.png)

The progress bars are not working when I sign into the website but when I sign out they are being displayed.

**Comment by Ahmad-A0** [comment]
I think this is a duplicate of #580, please reopen if this isn't the case.

**Comment by Vamsi995** [comment]
Yes it is the same issue.
