### ISSUE TITLE
Github Link wrong

### ISSUE THREAD

**Issue by RafaelBod** [neetcode-gh/leetcode#847]
Not sure if that's the place to put it. But I noticed the Python link for the problem Pow(x, n) on neetcode.io seems to be wrong.
Currently it's
https://github.com/neetcode-gh/leetcode/blob/main/python/50-Pow(x%2C%20n)
which yields a 404
It should probably be changed to:
https://github.com/neetcode-gh/leetcode/blob/main/python/50-Pow(x%2C%20n).py

**Comment by Ahmad-A0** [comment]
Sorry! I've renamed the file temporarily and hopefully @neetcode-gh can update the link and revert my commit.

**Comment by neetcode-gh** [comment]
Fixed.
