### ISSUE TITLE
RFE: Close Code Popup Modal on "Esc" key press

### ISSUE THREAD

**Issue by dgaikwad** [neetcode-gh/leetcode#956]
It would be good and convenient if we added the ability to close the Code Solution popup modal on "esc" keypress.

![Selection_367](https://user-images.githubusercontent.com/23401179/187079170-e7279120-b73f-4c1d-bf6a-242142a46dd3.png)

**Comment by neetcode-gh** [comment]
Sorry it took so long, but this has been fixed.
