### ISSUE TITLE
Enhancement: Notes section for each question

### ISSUE THREAD

**Issue by jordin513** [neetcode-gh/leetcode#99]
Adding a section for users to type notes (cached in the browser perhaps) would be very helpful. The notes section on the Blind 75 excel sheet that NeetCode created was super helpful. I would love the ability to write my own notes on how I solved the problems. Thanks!

**Comment by Nasiff** [comment]
Bump. I was actually looking for this. Having a notes section will definitely make for a much better and more streamlined review!

**Comment by ajinsunny** [comment]
Yes @neetcode-gh , if you could post the drawings that you cover in the video onto the READ.md file for each problem. That would be very helpful. 

If time is constrained for you, at least writing a few bullet points for it would help. 

I could do this on my fork and then send a PR. Would you be open to merging it?
